Add support for genezio middlewares.
Genez-io/genezio pull request #578
Opened 2023-11-30 12:49 UTC by vladiulianbogdan

# Pull Request Template

## Type of change

- [x] 🍕 New feature

## Description

Add support for genezio middlewares. Now we can do something like

```
function GenezioInputInspector(callback: (...args: any[]) => void) {
    return function (value: any, context: any) {
        return async function (...args: any[]) {
            callback(...args)
            const result =  await value(...args);
            return result
        };
    };
}
```

```
@GenezioDeploy()
export class HelloWorld {

  constructor() {
    console.log("Constructor called!")
  }
  
  @GenezioAuth()
  helloAuth(context: GenezioContext) {
      console.log("context is ", context)
  }

  /**
  * Method that returns a "Hello world" message.
  */
  @GenezioInputInspector((x) => { console.log("New request received with parameters", x) })
  helloWorld(test: string) {
    console.log("Hello world request received!", test)

    return "Hello world!";
  }

  /**
   * Method that returns a personalized "Hello world" message.
   */
  @GenezioInputInspector((name, from, value) => {
    z.string().parse(name);
    z.string().parse(from);
    z.nativeEnum(Season).parse(value)
  })
  hello(name: string, from: string, value: Season): string {
    console.log(`Hello world request received with name ${name} from ${from} value ${value}!`)

    const message = `Hello, ${name}, from ${from} during this ${value}`;
    console.log(message)

    return message
  }
}
```

2023-12-04 19:10 UTC, costinsin requested changes

2023-12-04 19:12 UTC, costinsin commented
Just to be clear, this change does not add support for `GenezioInputInspector` or `GenezioAuth`, right? As I understand, it just stops striping decorators and updates to the latest proposal.

2023-12-05 09:45 UTC, vladiulianbogdan commented
> Just to be clear, this change does not add support for `GenezioInputInspector` or `GenezioAuth`, right? As I understand, it just stops striping decorators and updates to the latest proposal.

Yes.

2024-01-26 17:06 UTC, costinsin approved these changes

2024-01-26 17:06 UTC, costinsin commented on src/utils/configuration.ts
> +        .filter((a: any) => a !== undefined)
Please use unknown instead of any.
```suggestion
        .filter((a: unknown) => a !== undefined)
```

2024-01-26 17:29 UTC, merged