Gnz 1479 enforce return type checking for webhooks
Genez-io/genezio pull request #906
Opened 2024-03-19 12:25 UTC by Virgil993

# Pull Request Template

## Type of change

-   [ ] 🐛 Bug Fix
-   [ ] 🔥 Breaking change
-   [ ] 📝 Documentation Update

## Description

This PR aims to enforce the types used as parameters and as return types in Http Methods. We have decided to change the way we quide our users when working with WebHooks. We now aim to encourage the usage of the native node types for Request and for Response. As such, before generating the SDK, we check if the Http methods have the right configuration and if not, we don't continue the SDK generation

## Checklist

-   [ ] My code follows the contributor guidelines of this project;
-   [ ] I have updated the documentation;
-   [ ] I have added tests;
-   [ ] New and existing unit tests pass locally with my changes;

2024-03-19 12:49 UTC, stefandarius requested changes

2024-03-19 12:49 UTC, stefandarius commented on src/generateSdk/astGenerator/TsAstGenerator.ts
> +                    return { type: AstNodeType.UnsupportedType, name: escapedText };
I would perform an additional check here to see if the type is indeed a Request or Response type (should be an interface defined in @types/node), and if so, Map it to a `AstNodeType.RequestType/ResponseType` (you should also define those in `genezioModels`).
This way the check you perform later in the SDK generation would be much simpler and language-agnostic.

Take a look at this [example](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#type-checker-apis) on how to use the TypeChecker to get the type of a symbol.

2024-03-19 12:49 UTC, stefandarius commented on src/generateSdk/generateSdkApi.ts
> +        }
As we discussed yesterday, I would perform this check in the bundling step. The SDK generation may not even happed if the user chooses not to, but the code still has to be correct.

2024-03-20 10:56 UTC, stefandarius requested changes

2024-03-20 10:56 UTC, stefandarius commented on src/generateSdk/generateSdkApi.ts
> +
This makes the function a bit hard to read. I propose to refactor the `checkInvalidHttpMethods` function to integrate this logic and check the HTTP method for that class, and also throw a UserError if it finds any problems. I think it Is ok to throw there and show the errors for just one class at a time.
If the function finds no problems, it should just return void and continue execution.

2024-03-20 10:56 UTC, stefandarius commented on src/generateSdk/astGenerator/TsAstGenerator.ts
> +    UnsupportedType,
Remove this type since it is not used anymore

2024-03-20 10:56 UTC, stefandarius commented on src/generateSdk/astGenerator/TsAstGenerator.ts
> +                    }
I don't think this is enough. The user could define an interface called Request which would satisfy this check, but result in a runtime error. We should use the type checker to determine if that type really is the interface defined in @types/node

2024-03-20 10:56 UTC, stefandarius commented on src/generateSdk/generateSdkApi.ts
> +                    }
This is a lot of duplicated code here. This check should not be language-dependent, as we have the AST. Simply checking if the function has a single parameter of type `Request` and a return type of either `Response` or `Promise` with `generic = Response` should do the trick. There is no need to verify the names of the types here. The AST already did this

2024-03-21 08:25 UTC, stefandarius approved these changes

2024-03-21 08:25 UTC, stefandarius commented on src/generateSdk/generateSdkApi.ts
> +                    astMethod.returnType.type != AstNodeType.PromiseType ||
I would also add the possibility for the return type to be directly `ResponseType`, to make it generic for other languages that will never return promises.

2024-03-25 10:20 UTC, radu1122 commented on src/errors.ts
> +    return `Invalid http methods found, the following methods are invalid:\n${invalidHttpMethodsString}\n${colors.yellow(`Please check the documentation for more information about how to define http
this sound me more explicit that the return value of the HTTP method is not correct

2024-06-19 13:54 UTC, closed without merging