improvement: Improve genezio addClass output
Genez-io/genezio pull request #919
Opened 2024-03-26 15:52 UTC by bhavyastar

# Pull Request Template

## Type of change

-   [ ] 🍕 New feature
-   [ ] 🐛 Bug Fix
-   [ ] 🔥 Breaking change
-   [x] 🧑‍💻 Improvement
-   [ ] 📝 Documentation Update

## Description

This PR improves Genezio addClass output

## Checklist

-   [x] My code follows the contributor guidelines of this project;
-   [ ] I have updated the documentation;
-   [ ] I have added tests;
-   [ ] New and existing unit tests pass locally with my changes;

2024-03-26 15:52 UTC, bhavyastar commented
Please review this @andreia-oca

2024-03-27 08:11 UTC, andreia-oca requested changes

2024-04-10 06:53 UTC, bhavyastar commented
Hey @andreia-oca 
Can you please review the changes?

2024-04-10 13:55 UTC, andreia-oca approved these changes
LGTM! Thank you for your contributions 🎉

2024-04-10 14:02 UTC, andreia-oca commented on src/commands/addClass.ts
> +            `Please provide a class name with a valid class extension. Currently supporting:${supportedExtensionsString}`,
```suggestion
            `Please provide a class name with a valid class extension. Currently supporting: ${supportedExtensions}`,
```

2024-08-13 14:16 UTC, andreia-oca commented
This PR seems inactive - I will close it. If there are any changes to the branch, we can reopen it.

2024-08-13 14:16 UTC, closed without merging